blog/urls.py
from django.urls import path
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('version/', include(('version.urls', 'version'), namespace='version')),
    path('users/', include(('users.urls', 'users'), namespace='users'))
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models


NULLABLE = {'blank': True, 'null': True}


class Blog(models.Model):
    title = models.CharField(max_length=100, verbose_name='заголовок')
    slug = models.CharField(max_length=100, verbose_name='slug', **NULLABLE)
    description = models.TextField(verbose_name='описание', **NULLABLE)
    image = models.ImageField(upload_to='blog', verbose_name='изображение', **NULLABLE)
    created_date = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    published = models.BooleanField(default=True, verbose_name='публикация')
    views = models.PositiveIntegerField(default=0, verbose_name='просмотры')

    def __str__(self):
        return f'{self.title} {self.description} {self.image} {self.created_date} {self.published} {self.views}'

    class Meta:
        verbose_name = 'блог'
        verbose_name_plural = 'блоги'

blog/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DeleteView, DetailView, UpdateView
from pytils.translit import slugify

from blog.models import Blog


class BlogListView(ListView):
    model = Blog

    def get_queryset(self):
        queryset = super().get_queryset()
        available = self.request.GET.get('published')
        if available == 'instock':
            queryset = queryset.filter(published=True)
        elif available == 'outofstock':
            queryset = queryset.filter(published=False)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views += 1
        self.object.save()
        return self.object


class BlogCreateView(CreateView):
    model = Blog
    fields = ('title', 'description', 'image')
    success_url = reverse_lazy('blog:blog_list')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.slug = slugify(new_blog.title)
            if len(form.cleaned_data['description']) == 0:
                new_blog.published = False
            else:
                new_blog.published = True
            new_blog.save()
        return super().form_valid(form)


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'description', 'image')
    # success_url = reverse_lazy('blog:blog_detail')

    def get_success_url(self):
        return reverse('blog:blog_detail', args=[self.kwargs.get('pk')])

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.description)
            new_blog.save()

        return super().form_valid(form)


class BlogDeleteView(DeleteView):
    model = Blog
    success_url = reverse_lazy('blog:blog_list')

blog/templates/blog/blog_confirm_delete.html
{% extends 'blog/base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-8 mx-auto">
                <form class="row" method="post" enctype="multipart/form-data">
                    <div class="card">
                        <div class="card-body">
                            <p class="card-text"> Хотите удалить "{{ object.name }}"?</p>
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Удалить</button>
                            <a class="btn btn-dark" href="{% url 'blog:blog_list' %}" role="button">Назад</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_detail.html
{% extends 'blog/base.html' %}
{% load my_tag %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-text"><p class="card-header">{{ object.slug }}</p>
                    <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                         xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
                         preserveAspectRatio="xMidYMid slice" focusable="false">
                        <image href="{{ object.image | media_filter }}" width="100%" height="100%"/>
                    </svg>
                    <div class="card-body">
                        <p class="card-text">{{ object.title }}</p>
                        <p class="card-text">{{ object.description }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'blog:blog_list' %}" role="button">Назад</a>
                            </div>
                        </div>
                    </div>
                    <div class="card-footer">
                        Просмотры: {{ object.views }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

blog/templates/blog/blog_form.html
{% extends 'blog/base.html' %}
{% block content %}
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-8 mx-auto">
                <form class="row" method="post" enctype="multipart/form-data">
                    <div class="card">
                        <div class="card-body">
                            {% csrf_token %}
                            {{ form.as_p }}
                            {% if object %}
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                            {% else %}
                            <button type="submit" class="btn btn-primary">Создать</button>
                            {% endif %}
                            <a class="btn btn-dark" href="{% url 'blog:blog_list' %}" role="button">Назад</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

blog/templates/blog/blog_list.html
{% extends 'blog/base.html' %}
{% load my_tag %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
            {% for object in object_list %}
            <div class="col">
                <div class="card shadow-sm">
                    <svg class="bd-placeholder-img card-img-top" width="100%" height="225"
                         xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: Thumbnail"
                         preserveAspectRatio="xMidYMid slice" focusable="false">
                        <image href="{{ object.image | media_filter }}" width="100%" height="100%"/>
                    </svg>
                    <div class="card-body">
                        <p class="card-text">{{ object.title }}</p>
                        <p class="card-text">{{ object.description }}</p>
                        {% if object.description|length >= 1 %}
                        <p class="card-text">Есть публикация</p>
                        {% else %}
                        <p class="card-text">Нет публикаций</p>
                        {% endif %}
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'blog:blog_detail' object.pk %}"
                                   role="button">Описание</a>
                                <a class="btn btn-warning" href="{% url 'blog:blog_update' object.pk %}"
                                   role="button">Редактировать</a>
                                <a class="btn btn-danger" href="{% url 'blog:blog_delete' object.pk %}"
                                   role="button">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}