blog/urls.py
from django.urls import path
from blog.views import BlogListView, BlogDetailView, BlogCreateView, BlogUpdateView, BlogDeleteView

urlpatterns = [
    path('', BlogListView.as_view(), name='blog_list'),
    path('blog/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('blog/create/', BlogCreateView.as_view(), name='blog_create'),
    path('blog/<int:pk>/update/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog/<int:pk>/delete/', BlogDeleteView.as_view(), name='blog_delete'),

]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('main.urls', 'main'), namespace='main')),
    path('blog/', include(('blog.urls', 'blog'), namespace='blog')),
    path('version/', include(('version.urls', 'version'), namespace='version')),
    path('users/', include(('users.urls', 'users'), namespace='users'))
 ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.views import ProductListView, ProductDetailView, ProductCreateView, ProductUpdateView, ProductDeleteView

urlpatterns = [
    path('', ProductListView.as_view(), name='products_list'),
    path('main/<int:pk>/', cache_page(60)(ProductDetailView.as_view()), name='product_detail'),
    path('main/create/', ProductCreateView.as_view(), name='product_create'),
    path('main/<int:pk>/update/', ProductUpdateView.as_view(), name='product_update'),
    path('main/<int:pk>/delete/', ProductDeleteView.as_view(), name='product_delete'),

]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.views import UserCreateView, email_confirmation, PasswordRecoveryView

urlpatterns = [
    path('login/', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserCreateView.as_view(), name='register'),
    path('email-confirm/<str:token>/', email_confirmation, name='email'),
    path('password-reset/', PasswordRecoveryView.as_view(), name='password_reset'),

]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from blog.models import NULLABLE


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='Email')
    phone = models.CharField(max_length=50, **NULLABLE, verbose_name='Телефон')
    avatar = models.ImageField(upload_to='users/avatars/', verbose_name='Аватар', **NULLABLE)
    country = models.CharField(max_length=50, verbose_name='страна', **NULLABLE)
    token = models.CharField(max_length=150, verbose_name='токен', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'пользователь'
        verbose_name_plural = 'пользователи'

    def __str__(self):
        return self.email

users/forms.py
from django.contrib.auth.forms import UserCreationForm

from main.forms import StyleFormMixin
from users.models import User
from django import forms


class UsersForm(StyleFormMixin, UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class PasswordRecoveryForm(StyleFormMixin, forms.Form):
    email = forms.EmailField(label='Адрес электронной почты')

users/views.py
import secrets
import random

from django.contrib.auth.hashers import make_password
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, FormView

from config.settings import EMAIL_HOST_USER
from users.forms import UsersForm, PasswordRecoveryForm
from users.models import User


class UserCreateView(CreateView):
    model = User
    form_class = UsersForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        user = form.save()
        user.is_active = False
        token = secrets.token_hex(16)
        user.token = token
        user.save()
        host = self.request.get_host()
        url = f'http://{host}/users/email-confirm/{token}/'
        send_mail(
            subject='Подтверждение почты',
            message=f'Подтвердите почту перйда по ссылке {url}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email]
        )
        return super().form_valid(form)


def email_confirmation(request, token):
    user = get_object_or_404(User, token=token)
    user.is_active = True
    user.save()
    return redirect(reverse('users:login'))


class PasswordRecoveryView(FormView):
    template_name = 'users/password_recovery.html'
    form_class = PasswordRecoveryForm
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        email = form.cleaned_data['email']
        try:
            user = get_object_or_404(User, email=email)
        except User.DoesNotExist:
            # Если пользователя с таким email нет, возвращаем ошибку
            form.add_error('email', 'Пользователь с таким email не существует')
            return super().form_invalid(form)

        new_password = ''.join(random.choices('abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', k=10))

        user.password = make_password(new_password)
        user.save()

        send_mail(
            subject='Восстановление пароля',
            message=f'Ваш новый пароль: {new_password}',
            from_email=EMAIL_HOST_USER,
            recipient_list=[user.email]
        )

        return super().form_valid(form)

users/templates/users/login.html
{% extends 'main/base.html' %}
{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-lg-6 col-md-8 mx-auto">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Войти</button>
                        <a class="btn btn-dark" href="{% url 'main:products_list' %}" role="button">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/password_recovery.html
{% extends 'main/base.html' %}
{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-lg-6 col-md-8 mx-auto">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Отправить</button>
                        <a class="btn btn-dark" href="{% url 'main:products_list' %}" role="button">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'main/base.html' %}
{% block content %}
<div class="container">
    <form class="row" method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-lg-6 col-md-8 mx-auto">
                <div class="card">
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">Зарегестрироваться</button>
                        <a class="btn btn-dark" href="{% url 'main:products_list' %}" role="button">Назад</a>
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}